# add job should trigger every hour
# i should only tests on kalyani.specs
# use ubuntu 

name: Run kalyani.specs

on:
  workflow_dispatch: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
      - cron: '0 * * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Check out repository code

