# add job should trigger every hour
# i should only tests on kalyani.specs
# use ubuntu 

name: Run kalyani.specs

on:
  workflow_dispatch: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
      - cron: '* * * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Check out repository code

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install packages
      run: npm install

    - name: Install Playwright browsers
      run: npx playwright install
   
    - name: run tests
      run: npm practrice workflow
